-- CreateEnum
CREATE TYPE "Role" AS ENUM ('ADMIN', 'NATIONAL', 'REGIONAL', 'DISTRICT', 'FACILITY');

-- CreateEnum
CREATE TYPE "JurisdictionLevel" AS ENUM ('NATIONAL', 'REGIONAL', 'DISTRICT', 'FACILITY');

-- CreateEnum
CREATE TYPE "SyncStatus" AS ENUM ('SUCCESS', 'FAILED', 'RUNNING');

-- CreateTable
CREATE TABLE "Submission" (
    "id" TEXT NOT NULL,
    "data" JSONB NOT NULL,
    "submissionDate" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "A_1_Respondent_type" TEXT,
    "A_1_Facility_type" TEXT,
    "A_2_Name_of_reporting_unit" TEXT,
    "A_3_Region" TEXT,
    "A_4_1_District_Central_Region" TEXT,
    "A_4_2_District_Eastern_Region" TEXT,
    "A_4_3_District_Northern_Region" TEXT,
    "A_4_4_District_Western_Region" TEXT,
    "A_5_Reporting_period_quarter" TEXT,
    "A_6_Date_of_submission_yyyy_mm_dd" TIMESTAMP(3),
    "A_8_Designation_role" TEXT,
    "region" TEXT,
    "district" TEXT,
    "facility" TEXT,
    "total_calhiv_at_hf" INTEGER,
    "calhiv_3_5_9_kg" INTEGER,
    "calhiv_6_9_9_kg" INTEGER,
    "calhiv_10_13_9_kg" INTEGER,
    "calhiv_14_19_9_kg" INTEGER,
    "calhiv_20_24_9_kg" INTEGER,
    "B_2_6_How_many_ALHIV_ving_care_at_this_HF" INTEGER,
    "calhiv_greater_than_25_kg" INTEGER,
    "B_2_8_How_many_ALHIV_ving_care_at_this_HF" INTEGER,
    "B_3_1_Number_CLHIV_0_4_yrs" INTEGER,
    "B_3_2_How_many_CLHIV_5_9" INTEGER,
    "B_3_3_How_many_ALHIV_aged_10_1" INTEGER,
    "B_3_4_No_ALHIV_aged_15_19" INTEGER,
    "C_1_1_How_many_CLHIV_non_pALD_formulation" INTEGER,
    "C_1_2_How_many_CLHIV_non_pALD_formulation" INTEGER,
    "C_1_3_How_many_CLHIV_non_pALD_formulation" INTEGER,
    "C_1_4_How_many_CLHIV_non_pALD_formulation" INTEGER,
    "C_1_5_How_many_CLHIV_non_pALD_formulation" INTEGER,
    "C_1_6_How_many_ALHIV_non_pALD_formulation" INTEGER,
    "C_1_7_How_many_ALHIV_non_pALD_formulation" INTEGER,
    "C_2_1_How_many_CLHIV_non_pALD_formulation" INTEGER,
    "C_2_2_How_many_CLHIV_non_pALD_formulation" INTEGER,
    "C_2_3_How_many_ALHIV_non_pALD_formulation" INTEGER,
    "C_2_4_How_many_ALHIV_non_pALD_formulation" INTEGER,
    "C_3_1_How_many_CLHIV_mg_pALD_formulation" INTEGER,
    "C_3_2_How_many_CLHIV_mg_pALD_formulation" INTEGER,
    "C_3_3_How_many_CLHIV_mg_pALD_formulation" INTEGER,
    "C_3_4_How_many_CLHIV_mg_pALD_formulation" INTEGER,
    "C_3_5_How_many_CLHIV_mg_pALD_formulation" INTEGER,
    "pald_3_5_9_kg" INTEGER,
    "pald_6_9_9_kg" INTEGER,
    "pald_10_13_9_kg" INTEGER,
    "pald_14_19_9_kg" INTEGER,
    "pald_20_24_9_kg" INTEGER,
    "C_5_1_How_many_CLHIV_mg_pALD_formulation" INTEGER,
    "C_5_2_How_many_CLHIV_mg_pALD_formulation" INTEGER,
    "C_5_3_How_many_ALHIV_mg_pALD_formulation" INTEGER,
    "C_5_4_How_many_ALHIV_mg_pALD_formulation" INTEGER,
    "C_5_1_How_many_CLHIV_mg_pALD_formulation_001" INTEGER,
    "C_5_2_How_many_CLHIV_mg_pALD_formulation_001" INTEGER,
    "C_5_3_How_many_ALHIV_mg_pALD_formulation_001" INTEGER,
    "C_5_4_How_many_ALHIV_mg_pALD_formulation_001" INTEGER,
    "no_hf_staff_eligible_pald" INTEGER,
    "number_hf_staff_oriented_pald" INTEGER,
    "C_9_1_Has_this_HF_re_ved_pALD_orientation" TEXT,
    "C_9_2_Is_the_HF_curr_combination_of_pALD" TEXT,
    "E_1_1_Has_this_HF_re_ation_on_integration" TEXT,
    "total_number_of_staff_hf" INTEGER,
    "E_1_3_Is_the_HF_curr_integrating_services" TEXT,
    "B_4_4_If_yes_to_integrated_ser" TEXT,
    "number_at_hf_mixed_opd" INTEGER,
    "number_at_hf_clinic_day" INTEGER,
    "number_at_hf_other_models" INTEGER,
    "total_number_hw_at_site" INTEGER,
    "number_hw_trained_integra" INTEGER,
    "F_1_4_What_mode_of_training_in" TEXT,
    "F_1_5_Have_you_had_support_sup" TEXT,
    "F_1_6_Have_you_had_c_his_reporting_period" TEXT,
    "F_1_7_What_topics_areas_were" TEXT,
    "G_1_1_Which_of_the_f_t_this_HF_for_CALHIV" TEXT,
    "D_1_Which_of_the_following_sec" TEXT,
    "G_1_2_a_How_many_CAL_second_line_regimens" INTEGER,
    "G_1_2_b_How_many_CAL_second_line_regimen" INTEGER,
    "G_1_3_Which_of_the_f_t_this_HF_for_CALHIV" TEXT,
    "G_1_3_a_How_many_CAL_third_line_regimens" INTEGER,
    "F_2_1_Does_your_site_provide_p" TEXT,
    "G_3_1_What_is_the_cu_C_3TC_DTG_60_30_5_mg" INTEGER,
    "G_3_2_What_is_the_av_for_this_formulation" INTEGER,
    "G_3_3_What_is_the_mo_tock_MOS_available" INTEGER,
    "G_4_1_What_is_the_cu_or_ABC_3TC_120_60_mg" INTEGER,
    "G_4_2_What_is_the_av_for_this_formulation" INTEGER,
    "G_4_3_What_is_the_mo_tock_MOS_available" INTEGER,
    "G_5_1_What_is_the_cu_packs_for_DTG_10_mg" INTEGER,
    "G_5_2_What_is_the_av_for_this_formulation" INTEGER,
    "G_5_3_What_is_the_mo_tock_MOS_available" INTEGER,
    "G_6_1_What_is_the_cu_for_AZT_3TC_60_30_mg" INTEGER,
    "G_6_2_What_is_the_av_for_this_formulation" INTEGER,
    "G_6_3_What_is_the_mo_tock_MOS_available" INTEGER,
    "H_1_1_How_many_CLHIV_his_reporting_period" INTEGER,
    "H_1_2_How_many_CLHIV_his_reporting_period" INTEGER,
    "H_1_3_How_many_CLHIV_ays_of_disengagement" INTEGER,
    "H_1_4_How_many_CLHIV_g_during_this_period" INTEGER,
    "H_1_5_How_many_CLHIV_iven_as_a_percentage" INTEGER,
    "H_1_6_How_many_had_C_ercentage_CD4_cutoff" INTEGER,
    "H_1_7_How_many_were_TB_LAM_and_GeneXpert" INTEGER,
    "H_1_8_How_many_teste_TBLAM_and_GeneXpert" INTEGER,
    "H_1_9_How_many_of_th_ed_anti_TB_treatment" INTEGER,
    "H_1_10_How_many_test_TBLAM_and_GeneXpert" INTEGER,
    "H_1_11_Of_those_who_ow_many_received_TPT" INTEGER,
    "H_1_12_How_many_received_CTX_prophylaxis" INTEGER,
    "H_1_13_How_many_were_nutrition_using_MUAC" INTEGER,
    "H_1_14_How_many_were_malnourished" INTEGER,
    "H_1_15_How_many_maln_ion_for_malnutrition" INTEGER,
    "H_2_1_How_many_CLHIV_his_reporting_period" INTEGER,
    "H_2_2_How_many_CLHIV_his_reporting_period" INTEGER,
    "H_2_3_How_many_CLHIV_ays_of_disengagement" INTEGER,
    "H_2_4_How_many_CLHIV_g_during_this_period" INTEGER,
    "H_2_5_How_many_CLHIV_had_a_CD4_test_done" INTEGER,
    "H_2_6_How_many_CLHIV_ad_CD4_200_cells_L" INTEGER,
    "H_2_7_How_many_were_TB_LAM_and_GeneXpert" INTEGER,
    "H_2_8_How_many_teste_TBLAM_and_GeneXpert" INTEGER,
    "H_2_9_How_many_of_th_ed_anti_TB_treatment" INTEGER,
    "H_2_10_How_many_test_TBLAM_and_GeneXpert" INTEGER,
    "H_2_11_Of_those_who_ow_many_received_TPT" INTEGER,
    "H_2_12_How_many_received_CTX_prophylaxis" INTEGER,
    "H_2_13_How_many_were_nutrition_using_MUAC" INTEGER,
    "H_2_14_How_many_were_malnourished" INTEGER,
    "H_2_15_How_many_maln_ion_for_malnutrition" INTEGER,
    "H_3_1_How_many_ALHIV_his_reporting_period" INTEGER,
    "H_3_2_How_many_ALHIV_his_reporting_period" INTEGER,
    "H_3_3_How_many_ALHIV_ays_of_disengagement" INTEGER,
    "H_3_4_How_many_ALHIV_creening_this_period" INTEGER,
    "H_3_5_How_many_ALHIV_had_a_CD4_test_done" INTEGER,
    "H_3_6_How_many_ALHIV_ad_CD4_200_cells_L" INTEGER,
    "H_3_7_How_many_were_TB_LAM_and_GeneXpert" INTEGER,
    "H_3_8_How_many_teste_TBLAM_and_GeneXpert" INTEGER,
    "H_3_9_How_many_of_th_ed_anti_TB_treatment" INTEGER,
    "H_3_10_How_many_test_TBLAM_and_GeneXpert" INTEGER,
    "H_3_11_Of_those_who_ow_many_received_TPT" INTEGER,
    "H_3_12_How_many_received_CTX_prophylaxis" INTEGER,
    "H_3_13_How_many_were_nutrition_using_MUAC" INTEGER,
    "H_3_14_How_many_were_malnourished" INTEGER,
    "H_3_15_How_many_maln_ion_for_malnutrition" INTEGER,
    "H_3_16_How_many_rece_test_10_years_only" INTEGER,
    "H_3_17_Of_those_who_many_tested_positive" INTEGER,
    "H_3_18_Of_those_who_ot_a_lumbar_puncture" INTEGER,
    "H_3_19_Of_those_who_a_negative_CSF_CRAG" INTEGER,
    "H_3_20_Of_those_who_re_emptive_treatment" INTEGER,
    "H_3_21_How_many_were_nt_in_the_past_month" INTEGER,
    "H_3_22_Of_those_that_atment_and_are_alive" INTEGER,
    "H_3_23_Of_those_that_how_many_were_LTFU" INTEGER,
    "H_3_24_Of_those_that_month_how_many_died" INTEGER,
    "H_3_25_Of_those_who_a_positive_CSF_CRAG" INTEGER,
    "H_3_26_Of_those_who_gitis_CM_treatment" INTEGER,
    "H_3_27_Of_those_who_nt_in_the_past_month" INTEGER,
    "H_3_28_How_many_were_nt_in_the_past_month" INTEGER,
    "H_3_29_Of_those_that_atment_and_are_alive" INTEGER,
    "H_3_30_Of_those_that_how_many_were_LTFU" INTEGER,
    "H_3_31_Of_those_that_month_how_many_died" INTEGER,
    "H_4_1_How_many_ALHIV_his_reporting_period" INTEGER,
    "H_4_2_How_many_ALHIV_his_reporting_period" INTEGER,
    "H_4_3_How_many_ALHIV_ays_of_disengagement" INTEGER,
    "H_4_4_How_many_ALHIV_creening_this_period" INTEGER,
    "H_4_5_How_many_ALHIV_had_a_CD4_test_done" INTEGER,
    "H_4_6_How_many_ALHIV_ad_CD4_200_cells_L" INTEGER,
    "H_4_7_How_many_were_TB_LAM_and_GeneXpert" INTEGER,
    "H_4_8_How_many_teste_TBLAM_and_GeneXpert" INTEGER,
    "H_4_9_How_many_of_th_ed_anti_TB_treatment" INTEGER,
    "H_4_10_How_many_test_TBLAM_and_GeneXpert" INTEGER,
    "H_4_11_Of_those_who_ow_many_received_TPT" INTEGER,
    "H_4_12_How_many_received_CTX_prophylaxis" INTEGER,
    "H_4_13_How_many_were_nutrition_using_MUAC" INTEGER,
    "H_4_14_How_many_were_malnourished" INTEGER,
    "H_4_15_How_many_maln_ion_for_malnutrition" INTEGER,
    "H_4_16_How_many_rece_test_10_years_only" INTEGER,
    "H_4_17_Of_those_who_any_tested_positive_" INTEGER,
    "H_4_18_Of_those_who_ot_a_lumbar_puncture" INTEGER,
    "H_4_19_Of_those_who_a_negative_CSF_CRAG" INTEGER,
    "H_4_20_Of_those_who_re_emptive_treatment" INTEGER,
    "H_4_21_How_many_were_nt_in_the_past_month" INTEGER,
    "H_4_22_Of_those_that_atment_and_are_alive" INTEGER,
    "H_4_23_Of_those_that_how_many_were_LTFU" INTEGER,
    "H_4_24_Of_those_that_month_how_many_died" INTEGER,
    "H_4_25_Of_those_who_a_positive_CSF_CRAG" INTEGER,
    "H_4_26_Of_those_who_gitis_CM_treatment" INTEGER,
    "H_4_27_Of_those_who_nt_in_the_past_month" INTEGER,
    "H_4_28_Of_those_who_nt_in_the_past_month" INTEGER,
    "H_4_29_Of_those_that_atment_and_are_alive" INTEGER,
    "H_4_30_Of_those_that_how_many_were_LTFU" INTEGER,
    "H_4_31_Of_those_that_month_how_many_died" INTEGER,
    "H_5_1_Does_this_HF_h_ate_Visitec_supplies" TEXT,
    "H_5_2_Availability_o_s_and_reagents_at_HF" TEXT,
    "H_5_3_Availability_o_CRAG_supplies_at_HF" TEXT,
    "H_5_4_Availability_o_CRAG_supplies_at_HF" TEXT,
    "H_5_5_Availability_o_PT_prophylaxis_at_HF" TEXT,
    "H_5_6_Availability_o_conazole_prophylaxis" TEXT,
    "H_5_7_Availability_of_CTX_prophylaxis" TEXT,
    "H_5_8_Availability_of_anti_TB_drugs" TEXT,
    "H_5_9_Availability_o_posomal_amphotericin" TEXT,
    "H_5_10_Availability_of_RUTF_75_and_100" TEXT,
    "H_5_11_Availability_of_dewormers" TEXT,
    "I_1_How_many_CALHIV_or_review_last_month" INTEGER,
    "I_1_1_Of_those_who_w_r_their_appointments" INTEGER,
    "I_1_2_For_those_who_id_the_HF_staff_take" TEXT,
    "J_1_1_Number_of_children_updat" INTEGER,
    "J_1_3_Number_of_chil_al_Load_0_4_years" INTEGER,
    "J_1_4_Number_of_children_supp" INTEGER,
    "J_2_1_Number_child_updated_vl" INTEGER,
    "J_2_3_Number_of_chil_al_Load_5_9_years" INTEGER,
    "J_2_4_Number_child_supp_vl" INTEGER,
    "J_3_1_Number_of_children_updat" INTEGER,
    "J_3_3_Number_of_chil_Load_10_14_years" INTEGER,
    "J_3_4_No_of_child_viral_supp" INTEGER,
    "J_4_1_No_an_updated_vl_15_19" INTEGER,
    "J_4_3_Number_missing_Load_15_19_years" INTEGER,
    "J_4_4_No_virally_suppressed" INTEGER,
    "J_5_1_tt_no_updated_vl_all" INTEGER,
    "J_5_3_Total_number_m_a_recent_Viral_Load" INTEGER,
    "J_5_4_Tt_no_of_CALHIV_supp" INTEGER,
    "K_1_1_No_clhiv_hlv_0_4" INTEGER,
    "K_1_2_Number_who_com_high_level_viraemia" INTEGER,
    "K_1_3_Number_who_com_high_level_viraemia" INTEGER,
    "K_1_4_Number_who_com_high_level_viraemia" INTEGER,
    "K_1_5_No_comp_3iac_0_4" INTEGER,
    "K_1_6_No_comp_4iac_0_4" INTEGER,
    "K_1_8_No_viral_supp_3iac_0_4" INTEGER,
    "K_1_10_Number_still_high_level_viraemia" INTEGER,
    "K_1_11_Number_referr_high_level_viraemia" INTEGER,
    "K_2_1_No_CALHIV_with_hlv" INTEGER,
    "K_2_2_Number_who_com_high_level_viraemia" INTEGER,
    "K_2_3_Number_who_com_high_level_viraemia" INTEGER,
    "K_2_4_Number_who_com_high_level_viraemia" INTEGER,
    "K_2_5_No_completed_3_iac_5_9" INTEGER,
    "K_2_6_No_completed_4_iac_5_9" INTEGER,
    "K_2_8_Number_who_ach_high_level_viraemia" INTEGER,
    "K_2_10_Number_still_high_level_viraemia" INTEGER,
    "K_2_11_Number_referr_high_level_viraemia" INTEGER,
    "K_3_1_No_of_CLHIV_hlv" INTEGER,
    "K_3_2_Number_who_com_high_level_viraemia" INTEGER,
    "K_3_3_Number_who_com_high_level_viraemia" INTEGER,
    "K_3_4_Number_who_com_high_level_viraemia" INTEGER,
    "K_3_5_No_completed_3_iac_10_14" INTEGER,
    "K_3_6_No_completed_4_iac_10_14" INTEGER,
    "K_3_8_No_achieved_supp_3_more" INTEGER,
    "K_3_10_Number_still_high_level_viraemia" INTEGER,
    "K_3_11_Number_referr_high_level_viraemia" INTEGER,
    "K_4_1_No_of_CALHIV_hlv" INTEGER,
    "K_4_2_Number_who_com_high_level_viraemia" INTEGER,
    "K_4_3_Number_who_com_high_level_viraemia" INTEGER,
    "K_4_4_Number_who_com_high_level_viraemia" INTEGER,
    "K_4_5_No_completed_3_iac" INTEGER,
    "K_4_6_No_completed_4_iac" INTEGER,
    "K_4_8_No_achieved_supp" INTEGER,
    "K_4_10_Number_still_high_level_viraemia" INTEGER,
    "K_4_11_Number_referr_high_level_viraemia" INTEGER,
    "L_1_1_No_of_CALHIV_with_llv" INTEGER,
    "L_1_2_Number_who_com_h_low_level_viraemia" INTEGER,
    "L_1_3_Number_who_com_h_low_level_viraemia" INTEGER,
    "L_1_4_Number_who_com_h_low_level_viraemia" INTEGER,
    "L_1_5_Number_who_com_h_low_level_viraemia" INTEGER,
    "L_1_6_Number_who_com_h_low_level_viraemia" INTEGER,
    "L_1_7_No_who_achieved_supp" INTEGER,
    "L_1_9_Number_still_w_h_low_level_viraemia" INTEGER,
    "L_2_1_No_CALHIV_with_llv" INTEGER,
    "L_2_2_Number_who_com_h_low_level_viraemia" INTEGER,
    "L_2_3_Number_who_com_h_low_level_viraemia" INTEGER,
    "L_2_4_Number_who_com_h_low_level_viraemia" INTEGER,
    "L_2_5_Number_who_com_h_low_level_viraemia" INTEGER,
    "L_2_6_Number_who_com_h_low_level_viraemia" INTEGER,
    "L_2_7_No_who_achieved_supp" INTEGER,
    "L_2_9_Number_still_w_h_low_level_viraemia" INTEGER,
    "L_3_1_No_of_CALHIV_with_llv" INTEGER,
    "L_3_2_Number_who_com_h_low_level_viraemia" INTEGER,
    "L_3_3_Number_who_com_h_low_level_viraemia" INTEGER,
    "L_3_4_Number_who_com_h_low_level_viraemia" INTEGER,
    "L_3_5_Number_who_com_h_low_level_viraemia" INTEGER,
    "L_3_6_Number_who_com_h_low_level_viraemia" INTEGER,
    "L_3_7_No_who_achieved_supp" INTEGER,
    "L_3_9_Number_still_w_h_low_level_viraemia" INTEGER,
    "L_4_1_No_of_CALHIV_llv" INTEGER,
    "L_4_2_Number_who_com_h_low_level_viraemia" INTEGER,
    "L_4_3_Number_who_com_h_low_level_viraemia" INTEGER,
    "L_4_4_Number_who_com_h_low_level_viraemia" INTEGER,
    "L_4_5_Number_who_com_h_low_level_viraemia" INTEGER,
    "L_4_6_Number_who_com_h_low_level_viraemia" INTEGER,
    "L_4_7_No_who_achieved_supp" INTEGER,
    "L_4_9_Number_still_w_h_low_level_viraemia" INTEGER,
    "M_1_1_No_enrolled_in_a_psy" INTEGER,
    "M_1_3_Number_enrolled_in_peer" INTEGER,
    "M_2_1_No_receiving_MMD_3" INTEGER,
    "M_2_3_Nuo_receiving_MMD_6" INTEGER,
    "M_3_1_No_under_Cddp" INTEGER,
    "M_3_3_No_under_Cclad" INTEGER,
    "M_3_5_No_under_Crpddp" INTEGER,
    "M_3_7_No_under_Fbim" INTEGER,
    "M_3_9_No_under_Fbg" INTEGER,
    "M_3_11_No_under_Ftdr" INTEGER,

    CONSTRAINT "Submission_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "SyncLog" (
    "id" SERIAL NOT NULL,
    "startedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "finishedAt" TIMESTAMP(3),
    "status" "SyncStatus" NOT NULL,
    "message" TEXT,
    "lastSubmissionDate" TIMESTAMP(3),

    CONSTRAINT "SyncLog_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "User" (
    "id" SERIAL NOT NULL,
    "email" TEXT NOT NULL,
    "passwordHash" TEXT NOT NULL,
    "role" "Role" NOT NULL,
    "jurisdictionLevel" "JurisdictionLevel" NOT NULL,
    "region" TEXT,
    "district" TEXT,
    "facility" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "User_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "User_email_key" ON "User"("email");
